version: '3.7'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=passin
    volumes:
      - 'db-data:/var/lib/postgresql/data'

  api-pass-in:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - 3001:3333
    environment:
      - DATABASE_URL=postgres://root:root@postgres:5432/passin
      - API_BASE_URL="http://localhost:3333"
    depends_on:
      - postgres

networks:
  passin:
    driver: bridge

volumes:
  db-data: