name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate sha
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
    
    - name: Build docker image
      run: docker build -t hmatheus00/nlw.service.passin:${{steps.generate_sha.outputs.sha}} . 

    - name: Log into container registry
      uses: docker/login-action@v3
      with:
        username: ${{ variables.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Push image
      run: |
        docker push hmatheus00/nlw.service.passin:${{steps.generate_sha.outputs.sha}}